### ISSUE TITLE
webhooks over https

### ISSUE THREAD

**Issue by anton-smagin** [BitGo/bitgo-docs#12] opened 2017-06-27 13:29 UTC
Hello,

I`m trying to use your api to transfer money via bitgo wallet. For triggering our company's business logic I would like to use webhooks, but our web application works only over https. Do your webhooks support https? Because now we just don't receive them over https url. 

Hope for your help

**Comment by omaidf** [comment] 2017-06-27 16:54
Hello Anton,

To investigate further, we'd like to request your webhook URL. Due to privacy concerns, we will carry this conversation forward in your BitGo support ticket.

**Comment by omaidf** [comment] 2017-06-27 18:58
The root cause of this behavior was due to an incomplete SSL certificate. Closing issue, will continue the correspondence in BitGo support ticket.

**Closed by omaidf** 2017-06-27 18:58 UTC
